pipeline {
    agent any

    parameters {
        string(name: 'inventory', defaultValue: 'dev', description: 'This is the inventory file for the environment to deploy configuration')
    }

    // stage('Clean up') {
    //     steps {
    //         script {
    //             sh 'echo "Cleaning up Stage"'
    //         }
    //     }
    // }
}
