pipeline {
    agent any

    parameters {
        string(name: 'inventory', defaultValue: '${inventory}', description: 'This is the inventory file for the environment to deploy configuration')
    }

    stages {
        stage('Clean up') {
            steps {
                script {
                    sh 'echo "Cleaning up Stage"'
                }
            }
        }
    }
}
