---
- name: Include dynamic variables
  hosts: all
  tasks: 
    - import_playbook: ../static-assignments/common-del.yml
    - include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: Webserver assignment
  hosts: webservers
  tasks:
    - import_playbook: ../static-assignments/uat-webservers.yml

- name: Loadbalancers assignment
  hosts: lb
  tasks:
    - import_playbook: ../static-assignments/loadbalancers.yml
    when: load_balancer_is_required