---
- hosts: all
- name: Include dynamic variables
  tasks: 
    - import_playbook: ../static-assignments/common-del.yml
    - include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: webservers
- name: Webserver assignment
  tasks:
    - import_playbook: ../static-assignments/uat-webservers.yml